server:
  port: 8081

spring:
  #db
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test_db

  #kafka
  kafka:
    bootstrap-servers: localhost:9092,localhost:9094
    consumer:
      group-id: product-created-events
      properties:
        spring:
          json:
            trusted:
              packages: "*"